export const object1 =
  // object below
  {
    result: {
      portfolio: {
        portfolio_name: "3215235",
        portfolio_status: "ACTIVE",
        agency: "AMERICAN FORCES INFORMATION SERVICE",
        agencyDisplay: "AFIS",
        last_modified: "2024-04-25 06:58:44",
        current_user_is_owner: true,
        current_user_is_manager: false,
        vendor: "AWS",
        pop_start_date: "2023-04-01",
        pop_end_date: "2024-03-31",
        description: "",
        is_archived: false,
        last_updated: "2024-04-25 06:58:44",
        last_cost_data_sync: "",
        funding_status: "ON_TRACK",
        environments: [
          {
            classification_level: "U",
            cloud_distinguisher: "",
            highest_information_level: "IL5",
            csp_display: "aws_il5_dev",
            dashboard_link: null,
            environment_status: "PROVISIONED",
            provisioned_date: "2024-04-24 13:58:33",
            provisioning_request_date: "",
            sys_created_on: "2024-04-25 13:56:45",
            sys_id: "17eaae5193b9ca107b99b1dcebba1081",
          },
          {
            classification_level: "S",
            cloud_distinguisher: "",
            highest_information_level: "IL6",
            csp_display: "aws_il6_dev",
            dashboard_link: null,
            environment_status: "PROVISIONED",
            provisioned_date: "2024-04-24 13:58:30",
            provisioning_request_date: "",
            sys_created_on: "2024-04-25 13:56:46",
            sys_id: "abeaee5193b9ca107b99b1dcebba101d",
          },
          {
            classification_level: "TS",
            cloud_distinguisher: "",
            highest_information_level: "TS",
            csp_display: "aws_ts_dev",
            dashboard_link: null,
            environment_status: "PROVISIONED",
            provisioned_date: "2024-04-24 13:58:24",
            provisioning_request_date: "",
            sys_created_on: "2024-04-25 13:56:48",
            sys_id: "7beaee5193b9ca107b99b1dcebba10af",
          },
        ],
        portfolio_users: {
          creator: {
            name: "David Pietrzak",
            first_name: "David",
            last_name: "Pietrzak",
            user_name: "david.pietrzak",
            email: "david.t.pietrzak.ctr@mail.mil",
            company$DISPLAY: "",
            mobile_phone: null,
            phone: null,
            home_phone: null,
            title: null,
            sys_id: "6b68d9be932402107b99b1dcebba101e",
            role: "Creator",
            company: "",
          },
          owner: {
            name: "David Pietrzak",
            first_name: "David",
            last_name: "Pietrzak",
            user_name: "david.pietrzak",
            email: "david.t.pietrzak.ctr@mail.mil",
            company$DISPLAY: "",
            mobile_phone: null,
            phone: null,
            home_phone: null,
            title: null,
            sys_id: "6b68d9be932402107b99b1dcebba101e",
            role: "Owner",
            company: "",
          },
          managers: [],
          viewers: [],
        },
        available_funds: "240000.00",
        total_portfolio_funds: "240000.00",
        period_funds_spent: "0.00",
        spend_monthly_average: "0.00",
        spend_last_month: "0.00",
        spend_last_month_trend: "0.00",
        spend_end_of_month_xaas_forecast: "0.00",
        spend_end_of_month_xaas_forecast_trend: "0.00",
        spend_end_of_period_forecast: "0.00",
        estimated_funds_available: "240000.00",
        estimated_funds_to_be_invoiced: "0.00",
        inPeriodClins: [
          "32ea6e5193b9ca107b99b1dcebba1091",
          "8feaae5193b9ca107b99b1dcebba1032",
          "b2eaae5193b9ca107b99b1dcebba1016",
          "b2eaae5193b9ca107b99b1dcebba101b",
          "b6eaae5193b9ca107b99b1dcebba1017",
          "baeaae5193b9ca107b99b1dcebba1018",
          "beeaae5193b9ca107b99b1dcebba1014",
          "beeaae5193b9ca107b99b1dcebba1019",
        ],
        task_order: {
          total_task_order_value: "600000.00",
          total_lifecycle_amount: "3559207.25",
          total_funds_spent: "0.00",
          total_obligated_funds: "520000.00",
          task_order_number: "1000000000000",
          task_order_status: "EXPIRED",
          sys_id: "baea6e5193b9ca107b99b1dcebba1090",
        },
        clins: [
          {
            clin_number: "0001",
            idiq_clin: "Unclassified XaaS",
            active: true,
            actual_funds_spent: "0",
            clin_status: "ON_TRACK",
            classification_level: "U",
            funds_obligated: "240000",
            funds_total: "240000",
            pop_start_date: "2024-03-14",
            pop_end_date: "2025-03-14",
            type: "CLOUD",
            sys_id: "32ea6e5193b9ca107b99b1dcebba1091",
            costs: [],
          },
          {
            clin_number: "0002",
            idiq_clin: "Unclassified Cloud Support",
            active: true,
            actual_funds_spent: "0",
            clin_status: "EXPIRED",
            classification_level: "",
            funds_obligated: "150000",
            funds_total: "150000",
            pop_start_date: "2023-04-01",
            pop_end_date: "2024-03-31",
            type: "NON_CLOUD",
            sys_id: "36ea6e5193b9ca107b99b1dcebba1092",
            costs: [],
          },
          {
            clin_number: "0003",
            idiq_clin: "Secret XaaS",
            active: true,
            actual_funds_spent: "0",
            clin_status: "EXPIRED",
            classification_level: "S",
            funds_obligated: "50000",
            funds_total: "100000",
            pop_start_date: "2023-04-01",
            pop_end_date: "2024-03-31",
            type: "CLOUD",
            sys_id: "3aea6e5193b9ca107b99b1dcebba1093",
            costs: [],
          },
          {
            clin_number: "0004",
            idiq_clin: "Secret Cloud Support",
            active: true,
            actual_funds_spent: "0",
            clin_status: "EXPIRED",
            classification_level: "",
            funds_obligated: "60000",
            funds_total: "75000",
            pop_start_date: "2023-04-01",
            pop_end_date: "2024-03-31",
            type: "NON_CLOUD",
            sys_id: "3eea6e5193b9ca107b99b1dcebba1094",
            costs: [],
          },
          {
            clin_number: "0302",
            idiq_clin: "Unclassified Cloud Support",
            active: true,
            actual_funds_spent: "0",
            clin_status: "OPTION_PENDING",
            classification_level: "",
            funds_obligated: "0",
            funds_total: "168000",
            pop_start_date: "2026-04-01",
            pop_end_date: "2027-03-31",
            type: "NON_CLOUD",
            sys_id: "83eaae5193b9ca107b99b1dcebba1025",
            costs: [],
          },
          {
            clin_number: "0306",
            idiq_clin: "Top Secret Cloud Support",
            active: true,
            actual_funds_spent: "20",
            clin_status: "OPTION_PENDING",
            classification_level: "",
            funds_obligated: "0",
            funds_total: "8400",
            pop_start_date: "2026-04-01",
            pop_end_date: "2027-03-31",
            type: "NON_CLOUD",
            sys_id: "83eaae5193b9ca107b99b1dcebba102a",
            costs: [
              {
                is_actual: true,
                value: 20.0,
                year_month: "2023-04-01",
                clin: "83eaae5193b9ca107b99b1dcebba102a",
                sys_id: "31fca71393ed82107b99b1dcebba10e3",
                clin_number: "0306",
              },
            ],
          },
          {
            clin_number: "0404",
            idiq_clin: "Secret Cloud Support",
            active: true,
            actual_funds_spent: "0",
            clin_status: "OPTION_PENDING",
            classification_level: "",
            funds_obligated: "0",
            funds_total: "84000",
            pop_start_date: "2027-04-01",
            pop_end_date: "2028-03-31",
            type: "NON_CLOUD",
            sys_id: "83eaae5193b9ca107b99b1dcebba102f",
            costs: [],
          },
          {
            clin_number: "0303",
            idiq_clin: "Secret XaaS",
            active: true,
            actual_funds_spent: "0",
            clin_status: "OPTION_PENDING",
            classification_level: "S",
            funds_obligated: "0",
            funds_total: "108000",
            pop_start_date: "2026-04-01",
            pop_end_date: "2027-03-31",
            type: "CLOUD",
            sys_id: "87eaae5193b9ca107b99b1dcebba1026",
            costs: [],
          },
          {
            clin_number: "0401",
            idiq_clin: "Unclassified XaaS",
            active: true,
            actual_funds_spent: "0",
            clin_status: "OPTION_PENDING",
            classification_level: "U",
            funds_obligated: "0",
            funds_total: "300000",
            pop_start_date: "2027-04-01",
            pop_end_date: "2028-03-31",
            type: "CLOUD",
            sys_id: "87eaae5193b9ca107b99b1dcebba102b",
            costs: [],
          },
          {
            clin_number: "0405",
            idiq_clin: "Top Secret XaaS",
            active: true,
            actual_funds_spent: "0",
            clin_status: "OPTION_PENDING",
            classification_level: "TS",
            funds_obligated: "0",
            funds_total: "18000",
            pop_start_date: "2027-04-01",
            pop_end_date: "2028-03-31",
            type: "CLOUD",
            sys_id: "87eaae5193b9ca107b99b1dcebba1030",
            costs: [],
          },
          {
            clin_number: "0304",
            idiq_clin: "Secret Cloud Support",
            active: true,
            actual_funds_spent: "0",
            clin_status: "OPTION_PENDING",
            classification_level: "",
            funds_obligated: "0",
            funds_total: "84000",
            pop_start_date: "2026-04-01",
            pop_end_date: "2027-03-31",
            type: "NON_CLOUD",
            sys_id: "8beaae5193b9ca107b99b1dcebba1027",
            costs: [],
          },
          {
            clin_number: "0402",
            idiq_clin: "Unclassified Cloud Support",
            active: true,
            actual_funds_spent: "0",
            clin_status: "OPTION_PENDING",
            classification_level: "",
            funds_obligated: "0",
            funds_total: "168000",
            pop_start_date: "2027-04-01",
            pop_end_date: "2028-03-31",
            type: "NON_CLOUD",
            sys_id: "8beaae5193b9ca107b99b1dcebba102c",
            costs: [],
          },
          {
            clin_number: "0406",
            idiq_clin: "Top Secret Cloud Support",
            active: true,
            actual_funds_spent: "0",
            clin_status: "OPTION_PENDING",
            classification_level: "",
            funds_obligated: "0",
            funds_total: "8400",
            pop_start_date: "2027-04-01",
            pop_end_date: "2028-03-31",
            type: "NON_CLOUD",
            sys_id: "8beaae5193b9ca107b99b1dcebba1031",
            costs: [],
          },
          {
            clin_number: "0301",
            idiq_clin: "Unclassified XaaS",
            active: true,
            actual_funds_spent: "0",
            clin_status: "OPTION_PENDING",
            classification_level: "U",
            funds_obligated: "0",
            funds_total: "26400",
            pop_start_date: "2026-04-01",
            pop_end_date: "2027-03-31",
            type: "CLOUD",
            sys_id: "8feaae5193b9ca107b99b1dcebba1023",
            costs: [],
          },
          {
            clin_number: "0305",
            idiq_clin: "Top Secret XaaS",
            active: true,
            actual_funds_spent: "0",
            clin_status: "OPTION_PENDING",
            classification_level: "TS",
            funds_obligated: "0",
            funds_total: "24000",
            pop_start_date: "2026-04-01",
            pop_end_date: "2027-03-31",
            type: "CLOUD",
            sys_id: "8feaae5193b9ca107b99b1dcebba1028",
            costs: [],
          },
          {
            clin_number: "0403",
            idiq_clin: "Secret XaaS",
            active: true,
            actual_funds_spent: "0",
            clin_status: "OPTION_PENDING",
            classification_level: "S",
            funds_obligated: "0",
            funds_total: "108000",
            pop_start_date: "2027-04-01",
            pop_end_date: "2028-03-31",
            type: "CLOUD",
            sys_id: "8feaae5193b9ca107b99b1dcebba102d",
            costs: [],
          },
          {
            clin_number: "9999",
            idiq_clin: "",
            active: true,
            actual_funds_spent: "0",
            clin_status: "OPTION_PENDING",
            classification_level: "",
            funds_obligated: "0",
            funds_total: "627607.25",
            pop_start_date: "2023-04-01",
            pop_end_date: "2028-03-31",
            type: "NON_CLOUD",
            sys_id: "8feaae5193b9ca107b99b1dcebba1032",
            costs: [],
          },
          {
            clin_number: "0102",
            idiq_clin: "Unclassified Cloud Support",
            active: true,
            actual_funds_spent: "0",
            clin_status: "OPTION_PENDING",
            classification_level: "",
            funds_obligated: "0",
            funds_total: "150000",
            pop_start_date: "2024-03-14",
            pop_end_date: "2025-03-14",
            type: "NON_CLOUD",
            sys_id: "b2eaae5193b9ca107b99b1dcebba1016",
            costs: [],
          },
          {
            clin_number: "0106",
            idiq_clin: "Top Secret Cloud Support",
            active: true,
            actual_funds_spent: "0",
            clin_status: "OPTION_PENDING",
            classification_level: "",
            funds_obligated: "0",
            funds_total: "12000",
            pop_start_date: "2024-04-01",
            pop_end_date: "2025-03-31",
            type: "NON_CLOUD",
            sys_id: "b2eaae5193b9ca107b99b1dcebba101b",
            costs: [],
          },
          {
            clin_number: "0204",
            idiq_clin: "Secret Cloud Support",
            active: true,
            actual_funds_spent: "0",
            clin_status: "OPTION_PENDING",
            classification_level: "",
            funds_obligated: "0",
            funds_total: "78000",
            pop_start_date: "2025-04-01",
            pop_end_date: "2026-03-31",
            type: "NON_CLOUD",
            sys_id: "b2eaae5193b9ca107b99b1dcebba1020",
            costs: [],
          },
          {
            clin_number: "0005",
            idiq_clin: "Top Secret XaaS",
            active: true,
            actual_funds_spent: "0",
            clin_status: "EXPIRED",
            classification_level: "TS",
            funds_obligated: "15000",
            funds_total: "25000",
            pop_start_date: "2023-04-01",
            pop_end_date: "2024-03-31",
            type: "CLOUD",
            sys_id: "b6eaae5193b9ca107b99b1dcebba1012",
            costs: [],
          },
          {
            clin_number: "0103",
            idiq_clin: "Secret XaaS",
            active: true,
            actual_funds_spent: "0",
            clin_status: "OPTION_PENDING",
            classification_level: "S",
            funds_obligated: "0",
            funds_total: "96000",
            pop_start_date: "2024-04-01",
            pop_end_date: "2025-03-31",
            type: "CLOUD",
            sys_id: "b6eaae5193b9ca107b99b1dcebba1017",
            costs: [],
          },
          {
            clin_number: "0201",
            idiq_clin: "Unclassified XaaS",
            active: true,
            actual_funds_spent: "0",
            clin_status: "OPTION_PENDING",
            classification_level: "U",
            funds_obligated: "0",
            funds_total: "264000",
            pop_start_date: "2025-04-01",
            pop_end_date: "2026-03-31",
            type: "CLOUD",
            sys_id: "b6eaae5193b9ca107b99b1dcebba101c",
            costs: [],
          },
          {
            clin_number: "0205",
            idiq_clin: "Top Secret XaaS",
            active: true,
            actual_funds_spent: "0",
            clin_status: "OPTION_PENDING",
            classification_level: "TS",
            funds_obligated: "0",
            funds_total: "24000",
            pop_start_date: "2025-04-01",
            pop_end_date: "2026-03-31",
            type: "CLOUD",
            sys_id: "b6eaae5193b9ca107b99b1dcebba1021",
            costs: [],
          },
          {
            clin_number: "0006",
            idiq_clin: "Top Secret Cloud Support",
            active: true,
            actual_funds_spent: "0",
            clin_status: "EXPIRED",
            classification_level: "",
            funds_obligated: "5000",
            funds_total: "10000",
            pop_start_date: "2023-04-01",
            pop_end_date: "2024-03-31",
            type: "NON_CLOUD",
            sys_id: "baeaae5193b9ca107b99b1dcebba1013",
            costs: [],
          },
          {
            clin_number: "0104",
            idiq_clin: "Secret Cloud Support",
            active: true,
            actual_funds_spent: "0",
            clin_status: "OPTION_PENDING",
            classification_level: "",
            funds_obligated: "0",
            funds_total: "72000",
            pop_start_date: "2024-04-01",
            pop_end_date: "2025-03-31",
            type: "NON_CLOUD",
            sys_id: "baeaae5193b9ca107b99b1dcebba1018",
            costs: [
              {
                is_actual: false,
                value: 2060.0,
                year_month: "2023-03-01",
                clin: "baeaae5193b9ca107b99b1dcebba1018",
                sys_id: "35fca71393ed82107b99b1dcebba10dd",
                clin_number: "0104",
              },
            ],
          },
          {
            clin_number: "0202",
            idiq_clin: "Unclassified Cloud Support",
            active: true,
            actual_funds_spent: "0",
            clin_status: "OPTION_PENDING",
            classification_level: "",
            funds_obligated: "0",
            funds_total: "156000",
            pop_start_date: "2025-04-01",
            pop_end_date: "2026-03-31",
            type: "NON_CLOUD",
            sys_id: "baeaae5193b9ca107b99b1dcebba101d",
            costs: [],
          },
          {
            clin_number: "0206",
            idiq_clin: "Top Secret Cloud Support",
            active: true,
            actual_funds_spent: "0",
            clin_status: "OPTION_PENDING",
            classification_level: "",
            funds_obligated: "0",
            funds_total: "8400",
            pop_start_date: "2025-04-01",
            pop_end_date: "2026-03-31",
            type: "NON_CLOUD",
            sys_id: "baeaae5193b9ca107b99b1dcebba1022",
            costs: [],
          },
          {
            clin_number: "0101",
            idiq_clin: "Unclassified XaaS",
            active: true,
            actual_funds_spent: "0",
            clin_status: "OPTION_PENDING",
            classification_level: "U",
            funds_obligated: "0",
            funds_total: "240000",
            pop_start_date: "2024-04-01",
            pop_end_date: "2025-03-31",
            type: "CLOUD",
            sys_id: "beeaae5193b9ca107b99b1dcebba1014",
            costs: [],
          },
          {
            clin_number: "0105",
            idiq_clin: "Top Secret XaaS",
            active: true,
            actual_funds_spent: "0",
            clin_status: "OPTION_PENDING",
            classification_level: "TS",
            funds_obligated: "0",
            funds_total: "24000",
            pop_start_date: "2024-04-01",
            pop_end_date: "2025-03-31",
            type: "CLOUD",
            sys_id: "beeaae5193b9ca107b99b1dcebba1019",
            costs: [],
          },
          {
            clin_number: "0203",
            idiq_clin: "Secret XaaS",
            active: true,
            actual_funds_spent: "0",
            clin_status: "OPTION_PENDING",
            classification_level: "S",
            funds_obligated: "0",
            funds_total: "102000",
            pop_start_date: "2025-04-01",
            pop_end_date: "2026-03-31",
            type: "CLOUD",
            sys_id: "beeaae5193b9ca107b99b1dcebba101e",
            costs: [],
          },
        ],
      },
      portfolioId: "4beaae5193b9ca107b99b1dcebba1034",
    },
  };
